### ISSUE TITLE
Tabular output would be nice

### ISSUE THREAD

**Issue by erikrikarddaniel** [adw96/breakaway#77] opened 2020-01-08 16:07 UTC
The list output one gets today when inputting a matrix of feature counts in samples is difficult to deal with. It would be nice with a data.frame or other kind of table (sample, estimate, error, cilow, cihigh etc. as columns) as output option.

**Comment by adw96** [comment] 2020-01-09 19:26
Thanks for using breakaway! 

There are many different inputs to breakaway and so it's hard to know exactly what  type of data you have, but there is currently infrastructure for the following:

```
library(breakaway)
library(tidyverse)
library(phyloseq)
data("GlobalPatterns")
ba <- GlobalPatterns %>% 
  subset_samples(SampleType == "Soil") %>%
  breakaway
ba %>% summary
```

which gives you a tibble (modern alternative to a data frame) with the data that I think you want. Feel free to reopen if I misunderstood.

**Comment by adw96** [comment] 2020-01-09 19:27
Here's the output, of that call, FYI

```
# A tibble: 3 x 7
  estimate error lower   upper sample_names name      model
     <dbl> <dbl> <dbl>   <dbl> <chr>        <chr>     <chr>
1   11149. 2139. 6987. 754224. CL3          breakaway Kemp 
2   12334. 1985. 7708. 763048. CC1          breakaway Kemp 
3    8904. 1063. 5756. 373203. SV1          breakaway Kemp 
```

**Comment by erikrikarddaniel** [comment] 2020-01-10 07:45
Den tors 9 jan. 2020 kl 20:26 skrev AmyW <notifications@github.com>:
>
> Thanks for using breakaway!
>
> There are many different inputs to breakaway and so it's hard to know exactly what type of data you have, but there is currently infrastructure for the following:
>
> library(breakaway)
> library(tidyverse)
> library(phyloseq)
> data("GlobalPatterns")
> ba <- GlobalPatterns %>%
>   subset_samples(SampleType == "Soil") %>%
>   breakaway
> ba %>% summary
>
> which gives you a tibble (modern alternative to a data frame) with the data that I think you want. Feel free to reopen if I misunderstood.
>
Perfect, thanks for the explanation!

/Daniel

**Comment by SJohnsonMayo** [comment] 2020-01-14 21:56
Hello! 

I just tried this out, I'm having trouble reproducing this example:
```
> library(breakaway)
> library(tidyverse)
> library(phyloseq)
> data("GlobalPatterns")
> ba <- GlobalPatterns %>% 
+     subset_samples(SampleType == "Soil") %>%
+     breakaway
> ba %>% summary
# A tibble: 3 x 7
  estimate error lower   upper sample_names name      model
     <dbl> <dbl> <dbl>   <dbl> <chr>        <chr>     <chr>
1   11149. 2139. 6987. 754224. CL3          breakaway Kemp 
2   11149. 2139. 7708. 763048. CC1          breakaway Kemp 
3   11149. 2139. 5756. 373203. SV1          breakaway Kemp 
```

I think this may be due to the last line of the to_vector function:
```
to_vector <- function(object, piece) {
  unlisted_object <- object %>% lapply(function(x) {x[[piece]]}) %>% unlist 
                         ba %>% lapply(function(x) {x[[piece]]}) %>% unlist
  ifelse(is.null(unlisted_object), NA, unlisted_object)
}
```
It looks like that `is.null` only returns a single `TRUE` or `FALSE`, and apparently this forces the `ifelse` to just return a single estimate:
```
> test <- ba %>% lapply(function(x) {x[[piece]]}) %>% unlist
> ifelse(is.null(test), NA, test)
[1] 11148.98
```

If I try something like `is.na` instead I can get the other estimates:
```
> ifelse(is.na(test), NA, test)
      CL3       CC1       SV1 
11148.976 12333.547  8903.633
```

Thank you for your time!

Stephen

**Comment by adw96** [comment] 2020-01-14 23:02
@

**Comment by adw96** [comment] 2020-01-14 23:04
Thanks so much for bringing this to my attention,  @SJohnsonMayo . Indeed this is a bug, so I have reopened the issue. I just made a patch on the testing branch, so when it passes checks I will merge with master. Stay tuned...

**Comment by adw96** [comment] 2020-01-15 17:50
Just merged -- version 4.6.16 fixes this issue

**Closed by adw96** 2020-01-15 17:50 UTC

**Comment by SJohnsonMayo** [comment] 2020-01-28 22:01
Sorry to bring this up again! Just finally getting around to making sure I can get it to work on my own computer but still running into the same issue. I can see breakaway 4.6.16 in my sessionInfo so I think I'm working with the right version. There's definitely different estimates for each sample:
```
> ba
A collection of 3 alpha diversity estimates:

$ CL3
Estimate of richness from method breakaway:
  Estimate is 11149
 with standard error 2139.11
  Confidence interval: (6987, 754224)


$ CC1
Estimate of richness from method breakaway:
  Estimate is 12334
 with standard error 1985.07
  Confidence interval: (7708, 763048)


$ SV1
Estimate of richness from method breakaway:
  Estimate is 8904
 with standard error 1062.61
  Confidence interval: (5756, 373203)
```

But I believe `summary` is coercing the estimates to be identical:
```
> summary(ba)
# A tibble: 3 x 7
  estimate error lower   upper sample_names name      model
     <dbl> <dbl> <dbl>   <dbl> <chr>        <chr>     <chr>
1   11149. 2139. 6987. 754224. CL3          breakaway Kemp 
2   11149. 2139. 7708. 763048. CC1          breakaway Kemp 
3   11149. 2139. 5756. 373203. SV1          breakaway Kemp 
```

**Comment by adw96** [comment] 2020-01-29 22:48
Not a problem, happy to help. Can you please run the below code for me and paste the output if there is still an issue?

```
devtools::install_github("adw96/breakaway")
library(breakaway)
library(phyloseq)
library(magrittr)
R.version
sessionInfo()

ba_raw <- GlobalPatterns %>%
  subset_samples(SampleType == "Soil") %>%
  breakaway 
ba <- ba_raw %>% 
  summary
ba_raw
ba
```

**Comment by SJohnsonMayo** [comment] 2020-01-29 23:06
Looks good! Not sure what changed (maybe I had the old version sticking around somehow?) but glad it's working now. Thank you for your time! 

```
> devtools::install_github("adw96/breakaway")
Skipping install of 'breakaway' from a github remote, the SHA1 (6da0cac3) has not changed since last install.
  Use `force = TRUE` to force installation
> library(breakaway)
> library(phyloseq)
> library(magrittr)
> R.version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes          
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5     phyloseq_1.30.0  breakaway_4.6.16

loaded via a namespace (and not attached):
 [1] Biobase_2.46.0      pkgload_1.0.2       jsonlite_1.6        splines_3.6.1      
 [5] foreach_1.4.7       assertthat_0.2.1    stats4_3.6.1        remotes_2.1.0      
 [9] sessioninfo_1.1.1   pillar_1.4.3        backports_1.1.5     lattice_0.20-38    
[13] glue_1.3.1          digest_0.6.23       XVector_0.26.0      colorspace_1.4-1   
[17] Matrix_1.2-18       plyr_1.8.5          pkgconfig_2.0.3     devtools_2.2.1     
[21] zlibbioc_1.32.0     purrr_0.3.3         scales_1.1.0        processx_3.4.1     
[25] tibble_2.1.3        mgcv_1.8-31         IRanges_2.20.1      ggplot2_3.2.1      
[29] usethis_1.5.1       ellipsis_0.3.0      withr_2.1.2         BiocGenerics_0.32.0
[33] lazyeval_0.2.2      cli_2.0.1           survival_3.1-8      crayon_1.3.4       
[37] memoise_1.1.0       ps_1.3.0            fs_1.3.1            fansi_0.4.1        
[41] nlme_3.1-143        MASS_7.3-51.5       pkgbuild_1.0.6      vegan_2.5-6        
[45] tools_3.6.1         data.table_1.12.8   prettyunits_1.1.0   lifecycle_0.1.0    
[49] stringr_1.4.0       Rhdf5lib_1.8.0      S4Vectors_0.24.1    munsell_0.5.0      
[53] cluster_2.1.0       callr_3.4.0         Biostrings_2.54.0   ade4_1.7-13        
[57] compiler_3.6.1      rlang_0.4.2         rhdf5_2.30.1        grid_3.6.1         
[61] iterators_1.0.12    biomformat_1.14.0   rstudioapi_0.10     igraph_1.2.4.2     
[65] testthat_2.3.1      gtable_0.3.0        codetools_0.2-16    multtest_2.42.0    
[69] curl_4.3            reshape2_1.4.3      R6_2.4.1            dplyr_0.8.3        
[73] rprojroot_1.3-2     permute_0.9-5       desc_1.2.0          ape_5.3            
[77] stringi_1.4.5       parallel_3.6.1      Rcpp_1.0.3          tidyselect_0.2.5   
> 
> data("GlobalPatterns")
> ba_raw <- GlobalPatterns %>% 
+     subset_samples(SampleType=="Soil") %>% 
+     breakaway
> ba <- ba_raw %>% 
+     summary
> ba
# A tibble: 3 x 7
  estimate error lower   upper sample_names name      model
     <dbl> <dbl> <dbl>   <dbl> <chr>        <chr>     <chr>
1   11149. 2139. 6987. 754224. CL3          breakaway Kemp 
2   12334. 1985. 7708. 763048. CC1          breakaway Kemp 
3    8904. 1063. 5756. 373203. SV1          breakaway Kemp 
```
