### ISSUE TITLE
Plug-in estimates and breakaway estimates are the same

### ISSUE THREAD

**Issue by jorondo1** [adw96/breakaway#174] opened 2022-10-17 15:49 UTC
Hi @adw96 !

I thought I posted this already but I can't find my issue anymore, sorry in advance if I double-posted. The required command outputs are [here.](https://github.com/adw96/breakaway/files/9801083/log.txt)

I am running the STAMPS2022 breakaway tutorial on my data and the comparison between breakaway adjustment and plug-in richness yields identical plots, even though I have a significant (orders-of-magnitude) differences in sequencing depth between my two sample types (Saliva and Feces), 

```
observed_phyloseq <- sample_richness(psObject)
data.frame("observed_richness" = (observed_phyloseq %>% summary)$estimate,
           "depth" = phyloseq::sample_sums(psObject),
           "type" = psObject %>% sample_data %>% get_variable("compart")) %>%
  ggplot(aes(x = depth, y = observed_richness, color = type)) + geom_point()
```
![Rplot02](https://user-images.githubusercontent.com/97983060/196220241-b2f14555-0221-45dc-9bc7-a37c347f512e.png)

```
ba <- breakaway(psObject, cutoff=Inf) # omitting cutoff produces the same results
p1 <- plot(ba, psObject, color = "compart")
p2 <- plot(observed_phyloseq, psObject, color = "compart")
grid.arrange(p2, p1, nrow = 2)
```
![Rplot03](https://user-images.githubusercontent.com/97983060/196223059-6a259e45-2461-46af-abef-442d28d319b7.png)

I do get a warning after running the breakaway function, but from reading previously posted issues it doesn't seem to be cause for alarm:
```
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In cutoff_wrap(my_data, requested = cutoff) :
  ignoring requested cutoff; it's too low
2: In cutoff_wrap(my_data, requested = cutoff) :
  ignoring requested cutoff; it's too low
```
And the contents of the two objects look like this:
```
> ba
$ GQ56
Estimate of richness from method breakaway:
  Estimate is 389
 with standard error 0
  Confidence interval: (NaN, NaN)
  Cutoff:  Inf

> observed_phyloseq
$ GQ56
Estimate of richness from method Plug-in:
  Estimate is 389
 with standard error 0
  Confidence interval: (389, 389)
```
Can you help me figure this out ?

Thanks in advance

**Comment by adw96** [comment] 2022-10-18 18:46
Thanks so much @jorondo1 -- I have some suspicions about what's happening. Two questions:

1. How are you producing your count matrix? Are you filtering singletons?
2. Could you please provide some example frequency count tables? 

I think I can diagnose given the above information.

**Comment by jorondo1** [comment] 2022-10-18 19:03
The counts matrix is a Sourmash output. Here is [a subset](https://usherbrooke-my.sharepoint.com/:u:/g/personal/ronj2303_usherbrooke_ca/EXceS6uP1rhMvTZ0iei4h8IBEGN9DOPsXQlgoWKfsSycgA?e=q2WZkH) of the phyloseq object I am using as input. I have not done any filtering, the counts are as-is.

Thanks a lot for your time!

**Comment by adw96** [comment] 2022-11-24 05:16
Interesting -- it looks like you have very few biological units that are observed infrequently. What breakaway is (reasonably) inferring from this is that there are few unobserved biological units, which is why breakaway's estimates are the same as your plugin estimates. Basically if your data structure doesn't suggest that you have anything that's rare, it will predict that you have nothing missing! This is definitely the intended behavior of breakaway, so I'm going to close it as an issue. I hope that helps answer your question! 

That said, given the extremely strong correlation between depth and observed richness, if you wanted to fit a model for richness adjusting for depth, you might consider fitting a model like `lm(sample_richness ~ your_covariates + depth)`. I don't recommend this often but given that you don't have the ability to estimate the # of rare units (min hash sketches?), this might be the best you can do in this setting. 

Next time I chat with Taylor and Titus I might ask them about whether sourmash can detect rare/low abundance min hash sketches, since I'm ignorant on this.

**Closed** 2022-11-24 05:16 UTC
