### ISSUE TITLE
Breakaway package : Calculation of diversity Indices

### ISSUE THREAD

**Issue by sandipansamaddar** [adw96/breakaway#56] opened 2018-10-19 00:21 UTC
Hi,
I am studying the ammonia oxidizing archaeal diversity in long term fertilized paddy fields. Roche 454 was performed targeting the archaeal amoA gene and raw sequences were processed using Mothur. 
Following that, I would like to calculate the diversity indices using breakaway package. 

I have now the OTU table with me and would like to use it for calculation. I tried a few times to convert the table to frequency count table using the command build_frequency_count_tables(the_table), but was unable to do as I am not expert in R language. Below is a brief description how I processed.

**I created a .csv of my OTU table with title OTU_table.csv and imported it in R and then used:**
 
**build_frequency_count_tables(the_table = "OTU_table")**

but it showed

**Error in FUN(newX[, i], ...) : 
  breakaway no longer supports file paths as inputs**

On that note, if I can get some help on how can I proceed and calculate the indices it will be really appreciated. I am attaching the OTU table. It contains the OTU numbers in rows and treatments in columns. I have analyzed 5 treatments with three replicates each.
If you can kindly guide how should be the input format and also what will be the steps for calculation
it will be really helpful.

Thanks in advance.

Regards,

Sandipan

[OTU_table .xlsx](https://github.com/adw96/breakaway/files/2493992/OTU_table.xlsx)

**Comment by adw96** [comment] 2018-10-19 01:33
Hi -- as it states in the error message, breakaway does not accept file paths as inputs. You can either load your csv into a data frame or matrix in R and then run breakaway on that, or you can turn it into a phyloseq object and run breakaway on that. 

I recommend checking out the tutorial and trying to copy that:
https://github.com/adw96/stamps2018/blob/master/estimation/diversity-lab.R

Since this is a user error, not a bug, I'm closing this issue.

**Closed by adw96** 2018-10-19 01:33 UTC
